name: Python-Setup

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.0'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Python Version
      run: |
        # Command to verify the installed Python version
        python --version

    - name: Run Flake8 Linting
      run: |
        # Command to verify flake8 installation by checking its version
        flake8 --version

    - name: Run Pytest
      run: |
        # Command to verify pytest installation by checking its version
        pytest --version